services:
  - type: web
    name: titanio-app
    runtime: docker
    plan: free
    buildCommand: docker build -t titanio .
    startCommand: ./entrypoint.sh
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONPATH
        value: "/app"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"